services:
  api:
    image: chapi
    environment:
     - POSTGRES_PASSWORD=codeharmony
     - POSTGRES_HOST=postgres
    networks:
     - backend
     - frontend
  nginx:
    image: code_harmony_nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=codeharmony
    networks:
      - backend
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

networks:
  frontend:
  backend: